# Generated by Django migration generator for FAIRwDDI

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        help_text="Full persistent URN: urn:ddi:{agency}:{identifier}:{version}",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        default="fr.cdsp",
                        help_text="DDI maintenance agency identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "ddi_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Local or canonical identifier string within the agency scope.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Entity version string.", max_length=64
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Primary content digest (64-char hex string) for drift detection and deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "content_hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Multi-algorithm strategy hash digests dictionary.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual category label as an array of objects: [{'lang': 'fr', 'value': 'Tout à fait d\\'accord'}].",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "request_ddi_category",
            },
        ),
        migrations.CreateModel(
            name="CategorySet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        help_text="Full persistent URN: urn:ddi:{agency}:{identifier}:{version}",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        default="fr.cdsp",
                        help_text="DDI maintenance agency identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "ddi_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Local or canonical identifier string within the agency scope.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Entity version string.", max_length=64
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Primary content digest (64-char hex string) for drift detection and deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "content_hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Multi-algorithm strategy hash digests dictionary.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list, help_text="Multilingual name for the category set."
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True, default=list, help_text="Multilingual description."
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Set",
                "verbose_name_plural": "Category Sets",
                "db_table": "request_ddi_categoryset",
            },
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Authoritative concept URI in a controlled vocabulary or thesaurus.",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "vocabulary",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Controlled vocabulary name or scheme (e.g. 'ELSST', 'CESSDA Topics', 'DDI-CV').",
                        max_length=128,
                    ),
                ),
                (
                    "notation",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Standard thesaurus notation / classification code.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual concept label stored as an array of objects.",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual concept description stored as an array of objects.",
                    ),
                ),
                (
                    "definition",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual skos:definition stored as an array of objects.",
                    ),
                ),
                (
                    "concept_type",
                    models.CharField(
                        default="concept",
                        help_text="Concept classification type (e.g. 'domain', 'concept', 'thematic_group').",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent concept representing skos:broader hierarchical relationship.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="narrower_concepts",
                        to="fairwddi.concept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concept",
                "verbose_name_plural": "Concepts",
                "db_table": "request_ddi_concept",
            },
        ),
        migrations.CreateModel(
            name="Distributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Distributor",
                "verbose_name_plural": "Distributors",
                "db_table": "request_ddi_distributor",
            },
        ),
        migrations.CreateModel(
            name="QuestionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        help_text="Full persistent URN: urn:ddi:{agency}:{identifier}:{version}",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        default="fr.cdsp",
                        help_text="DDI maintenance agency identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "ddi_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Local or canonical identifier string within the agency scope.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Entity version string.", max_length=64
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Primary content digest (64-char hex string) for drift detection and deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "content_hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Multi-algorithm strategy hash digests dictionary.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_text",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual literal question text as an array of objects: [{'lang': 'fr', 'value': '...'}].",
                    ),
                ),
                (
                    "pre_question_text",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual introductory text / routing preamble.",
                    ),
                ),
                (
                    "post_question_text",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual post-question transition text.",
                    ),
                ),
                (
                    "interviewer_instructions",
                    models.JSONField(
                        blank=True, default=list, help_text="Multilingual interviewer guidance."
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Item",
                "verbose_name_plural": "Question Items",
                "db_table": "request_ddi_questionitem",
            },
        ),
        migrations.CreateModel(
            name="StagedImportPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_format",
                    models.CharField(
                        help_text="Source standard: 'ddi_l_3.3', 'ddi_l_4_json', 'ddi_c_2.5', 'croissant_1.0', 'csv'.",
                        max_length=64,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original uploaded filename.", max_length=512),
                ),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        help_text="File storage path for large XML/JSON/CSV file payloads.",
                        null=True,
                        upload_to="raw_imports/",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        help_text="Staged JSON representation of parsed raw file bundle.",
                        null=True,
                    ),
                ),
                (
                    "original_urns",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapping of original external URNs found in the raw file.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="staged",
                        help_text="Status: 'staged', 'harmonized', 'quarantined', 'failed'.",
                        max_length=32,
                    ),
                ),
                (
                    "import_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Link to background task queue.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Staged Import Payload",
                "verbose_name_plural": "Staged Import Payloads",
                "db_table": "request_ddi_stagedimportpayload",
            },
        ),
        migrations.CreateModel(
            name="URNAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alias_urn",
                    models.CharField(
                        help_text="The external, legacy, or random URN.",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "canonical_urn",
                    models.CharField(
                        db_index=True,
                        help_text="The resolved canonical database URN.",
                        max_length=512,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Target DDI entity type name (e.g. 'QuestionItem', 'CodeList').",
                        max_length=64,
                    ),
                ),
                (
                    "hash_strategy",
                    models.CharField(
                        default="v1_strict_sha256",
                        help_text="Strategy used to establish the canonical alias link.",
                        max_length=64,
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        help_text="Originating import filename for audit trail.",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "URN Alias",
                "verbose_name_plural": "URN Aliases",
                "db_table": "request_ddi_urnalias",
            },
        ),
        migrations.CreateModel(
            name="CodeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        help_text="Full persistent URN: urn:ddi:{agency}:{identifier}:{version}",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        default="fr.cdsp",
                        help_text="DDI maintenance agency identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "ddi_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Local or canonical identifier string within the agency scope.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Entity version string.", max_length=64
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Primary content digest (64-char hex string) for drift detection and deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "content_hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Multi-algorithm strategy hash digests dictionary.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual human title for the code list.",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True, default=list, help_text="Multilingual description."
                    ),
                ),
                (
                    "category_set",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to parent CategorySet scheme.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="code_lists",
                        to="fairwddi.categoryset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code List",
                "verbose_name_plural": "Code Lists",
                "db_table": "request_ddi_codelist",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual collection description stored as an array of objects.",
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        help_text="DDI-L Group URN.",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="fairwddi.distributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "db_table": "request_ddi_collection",
            },
        ),
        migrations.CreateModel(
            name="ConceptualVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        help_text="Full persistent URN: urn:ddi:{agency}:{identifier}:{version}",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        default="fr.cdsp",
                        help_text="DDI maintenance agency identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "ddi_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Local or canonical identifier string within the agency scope.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Entity version string.", max_length=64
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Primary content digest (64-char hex string) for drift detection and deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "content_hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Multi-algorithm strategy hash digests dictionary.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual conceptual variable label as an array of objects.",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual description as an array of objects.",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent concept anchor in a controlled vocabulary.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conceptual_variables",
                        to="fairwddi.concept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conceptual Variable",
                "verbose_name_plural": "Conceptual Variables",
                "db_table": "request_ddi_conceptualvariable",
            },
        ),
        migrations.CreateModel(
            name="ConceptRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        help_text="SKOS/XKOS relationship: broader, narrower, related, exactMatch, closeMatch, correspondsTo.",
                        max_length=64,
                    ),
                ),
                (
                    "target_uri",
                    models.CharField(
                        blank=True,
                        help_text="External URI if target concept is outside the local database.",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="fairwddi.concept",
                    ),
                ),
                (
                    "target_concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="fairwddi.concept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concept Relationship",
                "verbose_name_plural": "Concept Relationships",
                "db_table": "request_ddi_concept_relationship",
            },
        ),
        migrations.CreateModel(
            name="MetadataQuarantine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "incoming_urn",
                    models.CharField(help_text="URN of the conflicting element.", max_length=512),
                ),
                (
                    "existing_urn",
                    models.CharField(
                        blank=True,
                        help_text="URN of the conflicting database entity.",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("entity_type", models.CharField(help_text="DDI entity type name.", max_length=64)),
                (
                    "incoming_content",
                    models.JSONField(help_text="Full serialized payload of the incoming element."),
                ),
                (
                    "existing_content_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the existing record for comparison.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "incoming_content_hash",
                    models.CharField(help_text="Hash of the incoming element.", max_length=64),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        help_text="Reason: 'hash_mismatch', 'fuzzy_match', 'version_conflict'.",
                        max_length=32,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        help_text="Status: 'approved', 'forked', 'rejected', or null (pending).",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "resolved_by",
                    models.CharField(
                        blank=True,
                        help_text="Username of the reviewing archivist.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        help_text="Originating import filename.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "import_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Link to background task execution.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Metadata Quarantine Record",
                "verbose_name_plural": "Metadata Quarantine Records",
                "db_table": "request_ddi_metadataquarantine",
                "indexes": [
                    models.Index(fields=["resolution"], name="req_ddi_mq_resolution_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RepresentedVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        help_text="Full persistent URN: urn:ddi:{agency}:{identifier}:{version}",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        default="fr.cdsp",
                        help_text="DDI maintenance agency identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "ddi_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Local or canonical identifier string within the agency scope.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Entity version string.", max_length=64
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Primary content digest (64-char hex string) for drift detection and deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "content_hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Multi-algorithm strategy hash digests dictionary.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual short label as an array of objects.",
                    ),
                ),
                (
                    "code_list",
                    models.ForeignKey(
                        blank=True,
                        help_text="Response code structure (null for open-ended questions).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="represented_variables",
                        to="fairwddi.codelist",
                    ),
                ),
                (
                    "conceptual_variable",
                    models.ForeignKey(
                        help_text="Parent conceptual variable.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="represented_variables",
                        to="fairwddi.conceptualvariable",
                    ),
                ),
                (
                    "question_item",
                    models.ForeignKey(
                        help_text="Reusable question text component.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="represented_variables",
                        to="fairwddi.questionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Represented Variable",
                "verbose_name_plural": "Represented Variables",
                "db_table": "request_ddi_representedvariable",
            },
        ),
        migrations.CreateModel(
            name="StagedResourceNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="DDI entity type (e.g. 'QuestionItem', 'CodeList', 'Category', 'StudyUnit').",
                        max_length=64,
                    ),
                ),
                (
                    "raw_urn",
                    models.CharField(
                        db_index=True,
                        help_text="Raw external URN or local identifier from the source file.",
                        max_length=512,
                    ),
                ),
                (
                    "raw_value",
                    models.JSONField(
                        help_text="Un-harmonized raw JSON dictionary of fields/attributes."
                    ),
                ),
                (
                    "canonical_urn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Resolved canonical database URN after normalization.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="staged",
                        help_text="Status: 'staged', 'harmonized', 'quarantined', 'failed'.",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_payload",
                    models.ForeignKey(
                        help_text="Parent staged import bundle.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="fairwddi.stagedimportpayload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staged Resource Node",
                "verbose_name_plural": "Staged Resource Nodes",
                "db_table": "request_ddi_stagedresourcenode",
            },
        ),
        migrations.CreateModel(
            name="Subcollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        help_text="DDI-L SubGroup URN.",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcollections",
                        to="fairwddi.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcollection",
                "verbose_name_plural": "Subcollections",
                "db_table": "request_ddi_subcollection",
            },
        ),
        migrations.CreateModel(
            name="StudyUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        help_text="Full persistent URN: urn:ddi:{agency}:{identifier}:{version}",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        default="fr.cdsp",
                        help_text="DDI maintenance agency identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "ddi_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Local or canonical identifier string within the agency scope.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Entity version string.", max_length=64
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Primary content digest (64-char hex string) for drift detection and deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "content_hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Multi-algorithm strategy hash digests dictionary.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.JSONField(
                        default=list, help_text="Multilingual study title as an array of objects."
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        help_text="External identifier or DOI.",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Survey reference year.", null=True
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual study abstract/description as an array of objects.",
                    ),
                ),
                (
                    "subcollection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_units",
                        to="fairwddi.subcollection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Unit",
                "verbose_name_plural": "Study Units",
                "db_table": "request_ddi_studyunit",
            },
        ),
        migrations.CreateModel(
            name="InstanceVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        help_text="Full persistent URN: urn:ddi:{agency}:{identifier}:{version}",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        default="fr.cdsp",
                        help_text="DDI maintenance agency identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "ddi_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Local or canonical identifier string within the agency scope.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Entity version string.", max_length=64
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Primary content digest (64-char hex string) for drift detection and deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "content_hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Multi-algorithm strategy hash digests dictionary.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variable_name",
                    models.CharField(
                        help_text="Column name in the dataset (e.g. 'q01a', 'age_r').",
                        max_length=255,
                    ),
                ),
                (
                    "universe",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual target population/universe description as an array of objects.",
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual variable notes as an array of objects.",
                    ),
                ),
                (
                    "is_indexed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this variable is synchronized in Elasticsearch.",
                    ),
                ),
                (
                    "represented_variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_variables",
                        to="fairwddi.representedvariable",
                    ),
                ),
                (
                    "study_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_variables",
                        to="fairwddi.studyunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Variable",
                "verbose_name_plural": "Instance Variables",
                "db_table": "request_ddi_instancevariable",
                "unique_together": {("study_unit", "variable_name")},
            },
        ),
        migrations.CreateModel(
            name="VariableGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        help_text="Full persistent URN: urn:ddi:{agency}:{identifier}:{version}",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        default="fr.cdsp",
                        help_text="DDI maintenance agency identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "ddi_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Local or canonical identifier string within the agency scope.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Entity version string.", max_length=64
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Primary content digest (64-char hex string) for drift detection and deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "content_hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Multi-algorithm strategy hash digests dictionary.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual group title/label as an array of objects: [{'lang': 'fr', 'value': 'Démographie'}].",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual group description as an array of objects.",
                    ),
                ),
                (
                    "type_of_group",
                    models.CharField(
                        default="Thematic",
                        help_text="DDI-L typeOfVariableGroup (e.g. 'Thematic', 'QuestionnaireSection', 'Subject', 'Iteration').",
                        max_length=64,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link scoping this group across a series collection.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable_groups",
                        to="fairwddi.collection",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to controlled vocabulary concept.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variable_groups",
                        to="fairwddi.concept",
                    ),
                ),
                (
                    "parent_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent group for hierarchical group schemes.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subgroups",
                        to="fairwddi.variablegroup",
                    ),
                ),
                (
                    "study_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link scoping this group to a specific study wave.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable_groups",
                        to="fairwddi.studyunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variable Group",
                "verbose_name_plural": "Variable Groups",
                "db_table": "request_ddi_variablegroup",
            },
        ),
        migrations.CreateModel(
            name="CategorySetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within the category set."
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_set_memberships",
                        to="fairwddi.category",
                    ),
                ),
                (
                    "category_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fairwddi.categoryset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Set Item",
                "verbose_name_plural": "Category Set Items",
                "db_table": "request_ddi_categorysetitem",
                "ordering": ["order", "id"],
                "unique_together": {("category_set", "category")},
            },
        ),
        migrations.CreateModel(
            name="CodeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_value",
                    models.CharField(
                        help_text="The numerical or string code (e.g. '1', '98', 'Refused').",
                        max_length=64,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within the code list."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_memberships",
                        to="fairwddi.category",
                    ),
                ),
                (
                    "code_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fairwddi.codelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code Item",
                "verbose_name_plural": "Code Items",
                "db_table": "request_ddi_codeitem",
                "ordering": ["order", "id"],
                "unique_together": {("code_list", "code_value")},
            },
        ),
        migrations.CreateModel(
            name="VariableGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order of the variable within the group."
                    ),
                ),
                (
                    "instance_variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="fairwddi.instancevariable",
                    ),
                ),
                (
                    "variable_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="fairwddi.variablegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variable Group Membership",
                "verbose_name_plural": "Variable Group Memberships",
                "db_table": "request_ddi_variablegroupmembership",
                "ordering": ["order", "id"],
                "unique_together": {("variable_group", "instance_variable")},
            },
        ),
    ]
