# Generated by Django 6.0.8 on 2026-09-23 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('urn', models.CharField(help_text='Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}', max_length=512, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='Primary content digest (64-char hex) for drift detection and deduplication.', max_length=64)),
                ('content_hashes', models.JSONField(blank=True, default=dict, help_text='Multi-algorithm strategy hash digests dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.JSONField(default=list, help_text="Multilingual category label: [{'lang': 'fr', 'value': 'Tout à fait d'accord'}].")),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'request_ddi_category',
            },
        ),
        migrations.CreateModel(
            name='CategoryScheme',
            fields=[
                ('urn', models.CharField(help_text='Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}', max_length=512, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='Primary content digest (64-char hex) for drift detection and deduplication.', max_length=64)),
                ('content_hashes', models.JSONField(blank=True, default=dict, help_text='Multi-algorithm strategy hash digests dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=list, help_text='Multilingual name for the category scheme.')),
                ('description', models.JSONField(blank=True, default=list, help_text='Multilingual description.')),
            ],
            options={
                'verbose_name': 'Category Scheme',
                'verbose_name_plural': 'Category Schemes',
                'db_table': 'request_ddi_categoryscheme',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
                'db_table': 'request_ddi_distributor',
            },
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('urn', models.CharField(help_text='Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}', max_length=512, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='Primary content digest (64-char hex) for drift detection and deduplication.', max_length=64)),
                ('content_hashes', models.JSONField(blank=True, default=dict, help_text='Multi-algorithm strategy hash digests dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.JSONField(default=list, help_text="Multilingual literal question text: [{'lang': 'fr', 'value': '...'}].")),
                ('pre_question_text', models.JSONField(blank=True, default=list, help_text='Multilingual introductory text / routing preamble.')),
                ('post_question_text', models.JSONField(blank=True, default=list, help_text='Multilingual post-question transition text.')),
                ('interviewer_instructions', models.JSONField(blank=True, default=list, help_text='Multilingual interviewer guidance.')),
            ],
            options={
                'verbose_name': 'Question Item',
                'verbose_name_plural': 'Question Items',
                'db_table': 'request_ddi_questionitem',
            },
        ),
        migrations.CreateModel(
            name='StagedImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_format', models.CharField(help_text="Source format: 'ddi-l:3.3:xml', 'ddi-l:4.0:json', 'ddi-c:2.5:xml', 'croissant', 'csv'.", max_length=64)),
                ('file_name', models.CharField(help_text='Original uploaded filename.', max_length=512)),
                ('file_path', models.FileField(blank=True, help_text='File storage path for large XML/JSON/CSV file payloads.', null=True, upload_to='raw_imports/')),
                ('import_options', models.JSONField(blank=True, default=dict, help_text='Lightweight batch configuration and options passed with the upload.')),
                ('total_resources', models.IntegerField(default=0, help_text='Total staged resource nodes extracted from the payload.')),
                ('processed_resources', models.IntegerField(default=0, help_text='Count of successfully processed resource nodes.')),
                ('status', models.CharField(default='staged', help_text="Status: 'staged', 'normalized', 'quarantined', 'failed'.", max_length=32)),
                ('import_task_id', models.CharField(blank=True, help_text='Link to background task queue.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Staged Import',
                'verbose_name_plural': 'Staged Imports',
                'db_table': 'request_ddi_stagedimport',
            },
        ),
        migrations.CreateModel(
            name='StudyUnit',
            fields=[
                ('urn', models.CharField(help_text='Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}', max_length=512, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='Primary content digest (64-char hex) for drift detection and deduplication.', max_length=64)),
                ('content_hashes', models.JSONField(blank=True, default=dict, help_text='Multi-algorithm strategy hash digests dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(default=list, help_text='Multilingual study title as an array of objects.')),
                ('external_ref', models.CharField(blank=True, help_text='External identifier or DOI.', max_length=512, null=True, unique=True)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Survey reference year.', null=True)),
                ('description', models.JSONField(blank=True, default=list, help_text='Multilingual study abstract/description as an array of objects.')),
            ],
            options={
                'verbose_name': 'Study Unit',
                'verbose_name_plural': 'Study Units',
                'db_table': 'request_ddi_studyunit',
            },
        ),
        migrations.CreateModel(
            name='URNAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_urn', models.CharField(help_text='The external, legacy, or random URN.', max_length=512, unique=True)),
                ('canonical_urn', models.CharField(db_index=True, help_text='The resolved canonical database URN.', max_length=512)),
                ('entity_type', models.CharField(help_text="Target DDI entity type name (e.g. 'QuestionItem', 'CodeList').", max_length=64)),
                ('hash_strategy', models.CharField(default='v1_strict_sha256', help_text='Strategy used to establish the canonical alias link.', max_length=64)),
                ('source_file', models.CharField(blank=True, help_text='Originating import filename for audit trail.', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'URN Alias',
                'verbose_name_plural': 'URN Aliases',
                'db_table': 'request_ddi_urnalias',
            },
        ),
        migrations.CreateModel(
            name='CodeList',
            fields=[
                ('urn', models.CharField(help_text='Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}', max_length=512, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='Primary content digest (64-char hex) for drift detection and deduplication.', max_length=64)),
                ('content_hashes', models.JSONField(blank=True, default=dict, help_text='Multi-algorithm strategy hash digests dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(blank=True, default=list, help_text='Multilingual human title for the code list.')),
                ('description', models.JSONField(blank=True, default=list, help_text='Multilingual description.')),
                ('category_scheme', models.ForeignKey(blank=True, db_column='category_scheme_urn', help_text='Optional link to parent CategoryScheme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_lists', to='fairwddi.categoryscheme')),
            ],
            options={
                'verbose_name': 'Code List',
                'verbose_name_plural': 'Code Lists',
                'db_table': 'request_ddi_codelist',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, db_index=True, help_text='Authoritative concept URI in a controlled vocabulary or thesaurus.', max_length=512, null=True, unique=True)),
                ('vocabulary', models.CharField(blank=True, db_index=True, default='', help_text="Controlled vocabulary name or scheme (e.g. 'ELSST', 'CESSDA Topics', 'DDI-CV').", max_length=128)),
                ('notation', models.CharField(blank=True, db_index=True, help_text='Standard thesaurus notation / classification code.', max_length=128, null=True)),
                ('label', models.JSONField(default=list, help_text='Multilingual concept label stored as an array of objects.')),
                ('description', models.JSONField(blank=True, default=list, help_text='Multilingual concept description stored as an array of objects.')),
                ('definition', models.JSONField(blank=True, default=list, help_text='Multilingual skos:definition stored as an array of objects.')),
                ('concept_type', models.CharField(default='concept', help_text="Concept classification type (e.g. 'domain', 'concept', 'thematic_group').", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', help_text='Parent concept representing skos:broader hierarchical relationship.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrower_concepts', to='fairwddi.concept')),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
                'db_table': 'request_ddi_concept',
            },
        ),
        migrations.CreateModel(
            name='ConceptualVariable',
            fields=[
                ('urn', models.CharField(help_text='Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}', max_length=512, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='Primary content digest (64-char hex) for drift detection and deduplication.', max_length=64)),
                ('content_hashes', models.JSONField(blank=True, default=dict, help_text='Multi-algorithm strategy hash digests dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.JSONField(default=list, help_text='Multilingual conceptual variable label as an array of objects.')),
                ('description', models.JSONField(blank=True, default=list, help_text='Multilingual description as an array of objects.')),
                ('concept', models.ForeignKey(blank=True, db_column='concept_id', help_text='Optional parent concept anchor in a controlled vocabulary.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptual_variables', to='fairwddi.concept')),
            ],
            options={
                'verbose_name': 'Conceptual Variable',
                'verbose_name_plural': 'Conceptual Variables',
                'db_table': 'request_ddi_conceptualvariable',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('urn', models.CharField(help_text='Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}', max_length=512, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='Primary content digest (64-char hex) for drift detection and deduplication.', max_length=64)),
                ('content_hashes', models.JSONField(blank=True, default=dict, help_text='Multi-algorithm strategy hash digests dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.JSONField(blank=True, default=list, help_text='Multilingual collection description stored as an array of objects.')),
                ('distributor', models.ForeignKey(db_column='distributor_id', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='fairwddi.distributor')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'db_table': 'request_ddi_collection',
            },
        ),
        migrations.CreateModel(
            name='MetadataQuarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_urn', models.CharField(help_text='URN of the conflicting element.', max_length=512)),
                ('existing_urn', models.CharField(blank=True, help_text='URN of the conflicting database entity.', max_length=512, null=True)),
                ('entity_type', models.CharField(help_text='DDI entity type name.', max_length=64)),
                ('incoming_content', models.JSONField(help_text='Full serialized payload of the incoming element.')),
                ('existing_content_hash', models.CharField(blank=True, help_text='Hash of the existing record for comparison.', max_length=64, null=True)),
                ('incoming_content_hash', models.CharField(help_text='Hash of the incoming element.', max_length=64)),
                ('conflict_type', models.CharField(help_text="Reason: 'hash_mismatch', 'fuzzy_match', 'version_conflict'.", max_length=32)),
                ('resolution', models.CharField(blank=True, help_text="Status: 'approved', 'forked', 'rejected', or null (pending).", max_length=32, null=True)),
                ('resolved_by', models.CharField(blank=True, help_text='Username of the reviewing archivist.', max_length=255, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, help_text='Originating import filename.', max_length=512, null=True)),
                ('import_task_id', models.CharField(blank=True, help_text='Link to background task execution.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Metadata Quarantine Record',
                'verbose_name_plural': 'Metadata Quarantine Records',
                'db_table': 'request_ddi_metadataquarantine',
                'indexes': [models.Index(fields=['resolution'], name='req_ddi_mq_resolution_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('urn', models.CharField(help_text='Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}', max_length=512, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='Primary content digest (64-char hex) for drift detection and deduplication.', max_length=64)),
                ('content_hashes', models.JSONField(blank=True, default=dict, help_text='Multi-algorithm strategy hash digests dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.JSONField(default=list, help_text='Multilingual group title/label stored as an array of objects.')),
                ('description', models.JSONField(blank=True, default=list, help_text='Multilingual group description as an array of objects.')),
                ('parent_group', models.ForeignKey(blank=True, db_column='parent_group_urn', help_text='Optional parent group for hierarchical question groups.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroups', to='fairwddi.questiongroup')),
            ],
            options={
                'verbose_name': 'Question Group',
                'verbose_name_plural': 'Question Groups',
                'db_table': 'request_ddi_questiongroup',
            },
        ),
        migrations.CreateModel(
            name='RepresentedVariable',
            fields=[
                ('urn', models.CharField(help_text='Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}', max_length=512, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='Primary content digest (64-char hex) for drift detection and deduplication.', max_length=64)),
                ('content_hashes', models.JSONField(blank=True, default=dict, help_text='Multi-algorithm strategy hash digests dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.JSONField(blank=True, default=list, help_text='Multilingual short label as an array of objects.')),
                ('code_list', models.ForeignKey(blank=True, db_column='code_list_urn', help_text='Response code structure (null for open-ended questions).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_variables', to='fairwddi.codelist')),
                ('conceptual_variable', models.ForeignKey(db_column='conceptual_variable_urn', help_text='Parent conceptual variable.', on_delete=django.db.models.deletion.CASCADE, related_name='represented_variables', to='fairwddi.conceptualvariable')),
                ('question_item', models.ForeignKey(db_column='question_item_urn', help_text='Reusable question text component.', on_delete=django.db.models.deletion.CASCADE, related_name='represented_variables', to='fairwddi.questionitem')),
            ],
            options={
                'verbose_name': 'Represented Variable',
                'verbose_name_plural': 'Represented Variables',
                'db_table': 'request_ddi_representedvariable',
            },
        ),
        migrations.CreateModel(
            name='StagedResourceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(db_index=True, help_text="DDI entity type (e.g. 'QuestionItem', 'CodeList', 'Category', 'StudyUnit').", max_length=64)),
                ('raw_urn', models.CharField(db_index=True, help_text='Raw external URN or local identifier from the source file.', max_length=512)),
                ('raw_value', models.JSONField(help_text='Pre-normalized raw JSON dictionary of fields/attributes.')),
                ('canonical_urn', models.CharField(blank=True, db_index=True, help_text='Resolved canonical database URN after normalization.', max_length=512, null=True)),
                ('status', models.CharField(default='staged', help_text="Status: 'staged', 'normalized', 'quarantined', 'failed'.", max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staged_import', models.ForeignKey(help_text='Parent staged import bundle.', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='fairwddi.stagedimport')),
            ],
            options={
                'verbose_name': 'Staged Resource Node',
                'verbose_name_plural': 'Staged Resource Nodes',
                'db_table': 'request_ddi_stagedresourcenode',
            },
        ),
        migrations.CreateModel(
            name='InstanceVariable',
            fields=[
                ('urn', models.CharField(help_text='Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}', max_length=512, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='Primary content digest (64-char hex) for drift detection and deduplication.', max_length=64)),
                ('content_hashes', models.JSONField(blank=True, default=dict, help_text='Multi-algorithm strategy hash digests dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variable_name', models.CharField(help_text="Column name in the dataset (e.g. 'q01a', 'age_r').", max_length=255)),
                ('universe', models.JSONField(blank=True, default=list, help_text='Multilingual target population/universe description as an array of objects.')),
                ('notes', models.JSONField(blank=True, default=list, help_text='Multilingual variable notes as an array of objects.')),
                ('is_indexed', models.BooleanField(default=False, help_text='Whether this variable is synchronized in Elasticsearch.')),
                ('represented_variable', models.ForeignKey(db_column='represented_variable_urn', on_delete=django.db.models.deletion.CASCADE, related_name='instance_variables', to='fairwddi.representedvariable')),
                ('study_unit', models.ForeignKey(db_column='study_unit_urn', on_delete=django.db.models.deletion.CASCADE, related_name='instance_variables', to='fairwddi.studyunit')),
            ],
            options={
                'verbose_name': 'Instance Variable',
                'verbose_name_plural': 'Instance Variables',
                'db_table': 'request_ddi_instancevariable',
            },
        ),
        migrations.CreateModel(
            name='StudyUnitVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the variable within the study unit.')),
                ('instance_variable', models.ForeignKey(db_column='instance_variable_urn', on_delete=django.db.models.deletion.CASCADE, related_name='study_unit_links', to='fairwddi.instancevariable')),
                ('study_unit', models.ForeignKey(db_column='study_unit_urn', on_delete=django.db.models.deletion.CASCADE, related_name='study_unit_variables', to='fairwddi.studyunit')),
            ],
            options={
                'verbose_name': 'Study Unit Variable',
                'verbose_name_plural': 'Study Unit Variables',
                'db_table': 'request_ddi_studyunitvariable',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subcollection',
            fields=[
                ('urn', models.CharField(help_text='Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}', max_length=512, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='Primary content digest (64-char hex) for drift detection and deduplication.', max_length=64)),
                ('content_hashes', models.JSONField(blank=True, default=dict, help_text='Multi-algorithm strategy hash digests dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('collection', models.ForeignKey(db_column='collection_urn', on_delete=django.db.models.deletion.CASCADE, related_name='subcollections', to='fairwddi.collection')),
            ],
            options={
                'verbose_name': 'Subcollection',
                'verbose_name_plural': 'Subcollections',
                'db_table': 'request_ddi_subcollection',
            },
        ),
        migrations.AddField(
            model_name='studyunit',
            name='subcollection',
            field=models.ForeignKey(db_column='subcollection_urn', on_delete=django.db.models.deletion.CASCADE, related_name='study_units', to='fairwddi.subcollection'),
        ),
        migrations.CreateModel(
            name='CategorySchemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the category scheme.')),
                ('category', models.ForeignKey(db_column='category_urn', on_delete=django.db.models.deletion.CASCADE, related_name='category_scheme_memberships', to='fairwddi.category')),
                ('category_scheme', models.ForeignKey(db_column='category_scheme_urn', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fairwddi.categoryscheme')),
            ],
            options={
                'verbose_name': 'Category Scheme Item',
                'verbose_name_plural': 'Category Scheme Items',
                'db_table': 'request_ddi_categoryschemeitem',
                'ordering': ['order', 'id'],
                'unique_together': {('category_scheme', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_value', models.CharField(help_text="The numerical or string code (e.g. '1', '98', 'Refused').", max_length=64)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the code list.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(db_column='category_urn', on_delete=django.db.models.deletion.CASCADE, related_name='code_memberships', to='fairwddi.category')),
                ('code_list', models.ForeignKey(db_column='code_list_urn', on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='fairwddi.codelist')),
            ],
            options={
                'verbose_name': 'Code',
                'verbose_name_plural': 'Codes',
                'db_table': 'request_ddi_code',
                'ordering': ['order', 'id'],
                'unique_together': {('code_list', 'code_value')},
            },
        ),
        migrations.CreateModel(
            name='QuestionGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the question group.')),
                ('question_group', models.ForeignKey(db_column='question_group_urn', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fairwddi.questiongroup')),
                ('question_item', models.ForeignKey(db_column='question_item_urn', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='fairwddi.questionitem')),
            ],
            options={
                'verbose_name': 'Question Group Item',
                'verbose_name_plural': 'Question Group Items',
                'db_table': 'request_ddi_questiongroupitem',
                'ordering': ['order', 'id'],
                'unique_together': {('question_group', 'question_item')},
            },
        ),
        migrations.AddIndex(
            model_name='instancevariable',
            index=models.Index(fields=['is_indexed'], name='req_ddi_iv_is_indexed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instancevariable',
            unique_together={('study_unit', 'variable_name')},
        ),
        migrations.AlterUniqueTogether(
            name='studyunitvariable',
            unique_together={('study_unit', 'instance_variable')},
        ),
    ]
