# Generated by Django 6.0.8 on 2026-09-26 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryScheme",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual scheme name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual scheme description stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Scheme",
                "verbose_name_plural": "Category Schemes",
                "db_table": "request_ddi_categoryscheme",
            },
        ),
        migrations.CreateModel(
            name="ConceptScheme",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual scheme name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual scheme description stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Concept Scheme",
                "verbose_name_plural": "Concept Schemes",
                "db_table": "request_ddi_conceptscheme",
            },
        ),
        migrations.CreateModel(
            name="ConceptualVariableScheme",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual scheme name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual scheme description stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conceptual Variable Scheme",
                "verbose_name_plural": "Conceptual Variable Schemes",
                "db_table": "request_ddi_conceptualvariablescheme",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual description for the group.",
                        null=True,
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Group classification type (e.g. 'study_series', 'panel', 'thematic', 'collection').",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "references",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of referenced member resources: [{'resource_type': 'StudyUnit', 'urn': '...' }].",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "db_table": "request_ddi_group",
            },
        ),
        migrations.CreateModel(
            name="InstanceVariableScheme",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual scheme name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual scheme description stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Variable Scheme",
                "verbose_name_plural": "Instance Variable Schemes",
                "db_table": "request_ddi_instancevariablescheme",
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual human-readable title / label.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual description / abstract.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument",
                "verbose_name_plural": "Instruments",
                "db_table": "request_ddi_instrument",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Organization classification type (e.g. 'archive', 'distributor', 'funder').",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "request_ddi_organization",
            },
        ),
        migrations.CreateModel(
            name="QuestionScheme",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual scheme name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual scheme description stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Scheme",
                "verbose_name_plural": "Question Schemes",
                "db_table": "request_ddi_questionscheme",
            },
        ),
        migrations.CreateModel(
            name="RepresentedVariableScheme",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual scheme name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual scheme description stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Represented Variable Scheme",
                "verbose_name_plural": "Represented Variable Schemes",
                "db_table": "request_ddi_representedvariablescheme",
            },
        ),
        migrations.CreateModel(
            name="StagedImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_format",
                    models.CharField(
                        help_text="Source format: 'ddi-l:3.3:xml', 'ddi-l:4.0:json', 'ddi-c:2.5:xml', 'croissant', 'csv'.",
                        max_length=64,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original uploaded filename.", max_length=512),
                ),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        help_text="File storage path for large XML/JSON/CSV file payloads.",
                        null=True,
                        upload_to="raw_imports/",
                    ),
                ),
                (
                    "import_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Lightweight batch configuration and options passed with the upload.",
                    ),
                ),
                (
                    "total_resources",
                    models.IntegerField(
                        default=0,
                        help_text="Total staged resource nodes extracted from the payload.",
                    ),
                ),
                (
                    "processed_resources",
                    models.IntegerField(
                        default=0, help_text="Count of successfully processed resource nodes."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="staged",
                        help_text="Status: 'staged', 'normalized', 'quarantined', 'failed'.",
                        max_length=32,
                    ),
                ),
                (
                    "import_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Link to background task queue.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Staged Import",
                "verbose_name_plural": "Staged Imports",
                "db_table": "request_ddi_stagedimport",
            },
        ),
        migrations.CreateModel(
            name="StudyUnit",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual study title as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        help_text="External identifier or DOI.",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Survey reference year.", null=True
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual study abstract/description as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Unit",
                "verbose_name_plural": "Study Units",
                "db_table": "request_ddi_studyunit",
            },
        ),
        migrations.CreateModel(
            name="URNAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alias_urn",
                    models.CharField(
                        help_text="The external, legacy, or random URN.",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "canonical_urn",
                    models.CharField(
                        db_index=True,
                        help_text="The resolved canonical database URN.",
                        max_length=512,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Target DDI entity type name (e.g. 'QuestionItem', 'CodeList').",
                        max_length=64,
                    ),
                ),
                (
                    "hash_strategy",
                    models.CharField(
                        default="v1_strict_sha256",
                        help_text="Strategy used to establish the canonical alias link.",
                        max_length=64,
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        help_text="Originating import filename for audit trail.",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "URN Alias",
                "verbose_name_plural": "URN Aliases",
                "db_table": "request_ddi_urnalias",
            },
        ),
        migrations.CreateModel(
            name="UrnRegistry",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Canonical URN or external identifier/URI.",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Resource/entity type (e.g. 'QuestionItem', 'Category', 'ExternalConcept').",
                        max_length=64,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "URN Registry",
                "verbose_name_plural": "URN Registries",
                "db_table": "request_ddi_urnregistry",
            },
        ),
        migrations.CreateModel(
            name="CodeList",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True, default=list, help_text="Multilingual description.", null=True
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        db_column="scheme_urn",
                        help_text="Optional link to parent CategoryScheme.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="code_lists",
                        to="fairwddi.categoryscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code List",
                "verbose_name_plural": "Code Lists",
                "db_table": "request_ddi_codelist",
            },
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uri",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Authoritative concept URI in a controlled vocabulary or thesaurus.",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "vocabulary",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Controlled vocabulary name or scheme (e.g. 'ELSST', 'CESSDA Topics', 'DDI-CV').",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "notation",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Standard thesaurus notation / classification code.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual concept label stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual concept description stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "definition",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual skos:definition stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "concept_type",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Concept classification type (e.g. 'domain', 'concept', 'thematic_group').",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_urn",
                        help_text="Parent concept representing skos:broader hierarchical relationship.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="narrower_concepts",
                        to="fairwddi.concept",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        db_column="scheme_urn",
                        help_text="Parent ConceptScheme defining this concept.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="fairwddi.conceptscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concept",
                "verbose_name_plural": "Concepts",
                "db_table": "request_ddi_concept",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual category label: [{'lang': 'fr', 'value': '...' }].",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Display order within the category scheme.",
                        null=True,
                    ),
                ),
                (
                    "is_missing",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Indicates whether this category represents a missing or non-response value.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_urn",
                        help_text="Parent category for hierarchical category schemes.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="fairwddi.category",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        db_column="scheme_urn",
                        help_text="Parent CategoryScheme defining this category.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="fairwddi.categoryscheme",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="concept_urn",
                        help_text="Optional semantic concept anchor in a controlled vocabulary.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="fairwddi.concept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "request_ddi_category",
                "ordering": ["order", "urn"],
            },
        ),
        migrations.CreateModel(
            name="ConceptualVariable",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual conceptual variable label as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual description as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="concept_urn",
                        help_text="Optional parent concept anchor in a controlled vocabulary.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conceptual_variables",
                        to="fairwddi.concept",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        db_column="scheme_urn",
                        help_text="Parent ConceptualVariableScheme defining this conceptual variable.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceptual_variables",
                        to="fairwddi.conceptualvariablescheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conceptual Variable",
                "verbose_name_plural": "Conceptual Variables",
                "db_table": "request_ddi_conceptualvariable",
            },
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "urn",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical or source URN of the affected DDI resource.",
                        max_length=512,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the event occurred.",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Classification type (e.g. 'created', 'updated', 'quarantined', 'normalized').",
                        max_length=128,
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary event payload and metadata as JSONB.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Log",
                "verbose_name_plural": "Event Logs",
                "db_table": "request_ddi_eventlog",
                "ordering": ["-timestamp", "-id"],
                "indexes": [
                    models.Index(fields=["urn", "timestamp"], name="req_ddi_event_urn_ts_idx"),
                    models.Index(fields=["event_type"], name="req_ddi_event_type_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetadataQuarantine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "incoming_urn",
                    models.CharField(help_text="URN of the conflicting element.", max_length=512),
                ),
                (
                    "existing_urn",
                    models.CharField(
                        blank=True,
                        help_text="URN of the conflicting database entity.",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("entity_type", models.CharField(help_text="DDI entity type name.", max_length=64)),
                (
                    "incoming_content",
                    models.JSONField(help_text="Full serialized payload of the incoming element."),
                ),
                (
                    "existing_content_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the existing record for comparison.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "incoming_content_hash",
                    models.CharField(help_text="Hash of the incoming element.", max_length=64),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        help_text="Reason: 'hash_mismatch', 'fuzzy_match', 'version_conflict'.",
                        max_length=32,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        help_text="Status: 'approved', 'forked', 'rejected', or null (pending).",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "resolved_by",
                    models.CharField(
                        blank=True,
                        help_text="Username of the reviewing archivist.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        help_text="Originating import filename.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "import_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Link to background task execution.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Metadata Quarantine Record",
                "verbose_name_plural": "Metadata Quarantine Records",
                "db_table": "request_ddi_metadataquarantine",
                "indexes": [models.Index(fields=["resolution"], name="req_ddi_mq_resolution_idx")],
            },
        ),
        migrations.CreateModel(
            name="QuestionItem",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "response_domain",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object describing the response domain (e.g. {'type': 'code', 'code_list_urn': '...'}, {'type': 'numeric', ...}).",
                        null=True,
                    ),
                ),
                (
                    "question_text",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual literal question text: [{'lang': 'fr', 'value': '...'}].",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "code_list",
                    models.ForeignKey(
                        blank=True,
                        db_column="code_list_urn",
                        help_text="Associated response CodeList (null for non-coded response domains).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_items",
                        to="fairwddi.codelist",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        db_column="scheme_urn",
                        help_text="Parent QuestionScheme defining this question.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="fairwddi.questionscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Item",
                "verbose_name_plural": "Question Items",
                "db_table": "request_ddi_questionitem",
            },
        ),
        migrations.CreateModel(
            name="RepresentedVariable",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "value_representation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object describing the value representation (e.g. {'type': 'code', 'code_list_urn': '...'}, {'type': 'numeric', ...}).",
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual short label as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual description as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "code_list",
                    models.ForeignKey(
                        blank=True,
                        db_column="code_list_urn",
                        help_text="Response code structure (null for open-ended questions).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="represented_variables",
                        to="fairwddi.codelist",
                    ),
                ),
                (
                    "conceptual_variable",
                    models.ForeignKey(
                        blank=True,
                        db_column="conceptual_variable_urn",
                        help_text="Parent conceptual variable.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="represented_variables",
                        to="fairwddi.conceptualvariable",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        db_column="scheme_urn",
                        help_text="Parent RepresentedVariableScheme defining this represented variable.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="represented_variables",
                        to="fairwddi.representedvariablescheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Represented Variable",
                "verbose_name_plural": "Represented Variables",
                "db_table": "request_ddi_representedvariable",
            },
        ),
        migrations.CreateModel(
            name="InstanceVariable",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.JSONField(
                        default=list,
                        help_text="Multilingual name: [{'lang': 'fr', 'value': '...' }].",
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual variable label as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multilingual description as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        db_column="scheme_urn",
                        help_text="Parent InstanceVariableScheme defining this instance variable.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_variables",
                        to="fairwddi.instancevariablescheme",
                    ),
                ),
                (
                    "represented_variable",
                    models.ForeignKey(
                        blank=True,
                        db_column="represented_variable_urn",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_variables",
                        to="fairwddi.representedvariable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Variable",
                "verbose_name_plural": "Instance Variables",
                "db_table": "request_ddi_instancevariable",
            },
        ),
        migrations.CreateModel(
            name="SemanticRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        help_text="Resource type of the subject (e.g. 'Concept', 'ConceptualVariable', 'QuestionItem').",
                        max_length=128,
                    ),
                ),
                (
                    "subject_urn",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical URN or URI of the subject resource.",
                        max_length=512,
                    ),
                ),
                (
                    "predicate",
                    models.CharField(
                        db_index=True,
                        help_text="Relationship predicate (e.g. 'skos:exactMatch', 'skos:broadMatch', 'skos:closeMatch', 'skos:relatedMatch').",
                        max_length=256,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        help_text="Resource type of the object (e.g. 'Concept', 'ConceptualVariable', 'ExternalResource').",
                        max_length=128,
                    ),
                ),
                (
                    "object_urn",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical URN or URI of the object resource.",
                        max_length=512,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Semantic Relationship",
                "verbose_name_plural": "Semantic Relationships",
                "db_table": "request_ddi_semanticrelationship",
                "ordering": ["subject_urn", "predicate", "object_urn"],
                "indexes": [
                    models.Index(fields=["subject_urn", "predicate"], name="idx_semrel_sub_pred"),
                    models.Index(fields=["object_urn", "predicate"], name="idx_semrel_obj_pred"),
                    models.Index(fields=["predicate"], name="idx_semrel_predicate"),
                    models.Index(fields=["subject_type"], name="idx_semrel_sub_type"),
                    models.Index(fields=["object_type"], name="idx_semrel_obj_type"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject_urn", "predicate", "object_urn"), name="uq_semrel_triple"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StagedResourceNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="DDI entity type (e.g. 'QuestionItem', 'CodeList', 'Category', 'StudyUnit').",
                        max_length=64,
                    ),
                ),
                (
                    "raw_urn",
                    models.CharField(
                        db_index=True,
                        help_text="Raw external URN or local identifier from the source file.",
                        max_length=512,
                    ),
                ),
                (
                    "raw_value",
                    models.JSONField(
                        help_text="Pre-normalized raw JSON dictionary of fields/attributes."
                    ),
                ),
                (
                    "canonical_urn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Resolved canonical database URN after normalization.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="staged",
                        help_text="Status: 'staged', 'normalized', 'quarantined', 'failed'.",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staged_import",
                    models.ForeignKey(
                        help_text="Parent staged import bundle.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="fairwddi.stagedimport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staged Resource Node",
                "verbose_name_plural": "Staged Resource Nodes",
                "db_table": "request_ddi_stagedresourcenode",
            },
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "urn",
                    models.CharField(
                        help_text="Persistent canonical URN: urn:ddi:{agency}:{ID}:{version}",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code_value",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="The numerical or string code (e.g. '1', '98', 'Refused').",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Display order within the code list.",
                        null=True,
                    ),
                ),
                (
                    "is_missing",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Indicates whether this code represents a missing or non-response value.",
                        null=True,
                    ),
                ),
                (
                    "hashes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unified key-value hash digests dictionary (e.g. {'sha256': '...'}).",
                        null=True,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extended attributes stored as an array of objects.",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="category_urn",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_memberships",
                        to="fairwddi.category",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_urn",
                        help_text="Parent code for hierarchical code schemes.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="fairwddi.code",
                    ),
                ),
                (
                    "code_list",
                    models.ForeignKey(
                        blank=True,
                        db_column="code_list_urn",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="fairwddi.codelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code",
                "verbose_name_plural": "Codes",
                "db_table": "request_ddi_code",
                "ordering": ["order", "urn"],
                "unique_together": {("code_list", "code_value")},
            },
        ),
        migrations.CreateModel(
            name="InstrumentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencing path from instrument to question (e.g. sequence/flow path).",
                        max_length=512,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order or question sequence number within the instrument.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        db_column="instrument_urn",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_associations",
                        to="fairwddi.instrument",
                    ),
                ),
                (
                    "question_item",
                    models.ForeignKey(
                        db_column="question_item_urn",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_associations",
                        to="fairwddi.questionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument Question",
                "verbose_name_plural": "Instrument Questions",
                "db_table": "request_ddi_instrumentquestion",
                "ordering": ["order", "id"],
                "unique_together": {("instrument", "question_item", "path")},
            },
        ),
        migrations.CreateModel(
            name="QuestionVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencing path from question to variable (e.g. XPath/DDI reference path).",
                        max_length=512,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within the represented variable associations.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_item",
                    models.ForeignKey(
                        db_column="question_item_urn",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable_associations",
                        to="fairwddi.questionitem",
                    ),
                ),
                (
                    "represented_variable",
                    models.ForeignKey(
                        db_column="represented_variable_urn",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_associations",
                        to="fairwddi.representedvariable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Variable",
                "verbose_name_plural": "Question Variables",
                "db_table": "request_ddi_questionvariable",
                "ordering": ["order", "id"],
                "unique_together": {("question_item", "represented_variable")},
            },
        ),
        migrations.CreateModel(
            name="StudyUnitVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencing path from study unit to instance variable.",
                        max_length=512,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order of the variable within the study unit."
                    ),
                ),
                (
                    "instance_variable",
                    models.ForeignKey(
                        db_column="instance_variable_urn",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_unit_links",
                        to="fairwddi.instancevariable",
                    ),
                ),
                (
                    "study_unit",
                    models.ForeignKey(
                        db_column="study_unit_urn",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_unit_variables",
                        to="fairwddi.studyunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Unit Variable",
                "verbose_name_plural": "Study Unit Variables",
                "db_table": "request_ddi_studyunitvariable",
                "ordering": ["order", "id"],
                "unique_together": {("study_unit", "instance_variable")},
            },
        ),
    ]
