# Generated by Django 6.0.8 on 2026-08-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fairwddi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conceptrelationship",
            name="source_concept",
        ),
        migrations.RemoveField(
            model_name="conceptrelationship",
            name="target_concept",
        ),
        migrations.AlterField(
            model_name="category",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Primary content digest (64-char hex) for drift detection and deduplication.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="label",
            field=models.JSONField(
                default=list,
                help_text="Multilingual category label: [{'lang': 'fr', 'value': 'Tout à fait d'accord'}].",
            ),
        ),
        migrations.AlterField(
            model_name="categoryset",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Primary content digest (64-char hex) for drift detection and deduplication.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="codelist",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Primary content digest (64-char hex) for drift detection and deduplication.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="conceptualvariable",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Primary content digest (64-char hex) for drift detection and deduplication.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="instancevariable",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Primary content digest (64-char hex) for drift detection and deduplication.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="questionitem",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Primary content digest (64-char hex) for drift detection and deduplication.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="questionitem",
            name="question_text",
            field=models.JSONField(
                default=list,
                help_text="Multilingual literal question text: [{'lang': 'fr', 'value': '...'}].",
            ),
        ),
        migrations.AlterField(
            model_name="representedvariable",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Primary content digest (64-char hex) for drift detection and deduplication.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="stagedimportpayload",
            name="source_format",
            field=models.CharField(
                help_text="Source format: 'ddi_l_3.3', 'ddi_l_4_json', 'ddi_c_2.5', 'croissant', 'csv'.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="studyunit",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Primary content digest (64-char hex) for drift detection and deduplication.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="variablegroup",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Primary content digest (64-char hex) for drift detection and deduplication.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="variablegroup",
            name="label",
            field=models.JSONField(
                default=list,
                help_text="Multilingual group title/label stored as an array of objects.",
            ),
        ),
        migrations.AlterField(
            model_name="variablegroup",
            name="type_of_group",
            field=models.CharField(
                default="Thematic",
                help_text="DDI-L typeOfVariableGroup (e.g. 'Thematic', 'Section', 'Subject', 'Iteration').",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="instancevariable",
            index=models.Index(fields=["is_indexed"], name="req_ddi_iv_is_indexed_idx"),
        ),
        migrations.DeleteModel(
            name="ConceptRelationship",
        ),
    ]
